apiVersion: apps/v1
kind: Deployment
metadata:
  name: practo-scraper-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practo-scraper-worker
  template:
    metadata:
      labels:
        app: practo-scraper-worker
    spec:
      containers:
      - name: my-app-container
        image: magnuscarlsen26/practo-scraper-worker:latest
